### ISSUE TITLE
Add requirements.txt for Package Dependencies

### ISSUE THREAD

**Issue by MarcChen** [MarcChen/fashion-mnist-cGAN#6]
**Description**
We need a `requirements.txt` file in the repository to simplify the environment setup process. This file should list all the Python packages and their versions required to run the project smoothly.

**Tasks**
- [ ] Identify all necessary packages (e.g., `torch`, `torchvision`, `numpy`, `matplotlib`, `scikit-learn`, `pillow`, etc.)
- [ ] Specify compatible versions (to ensure reproducibility)
- [ ] Add the `requirements.txt` file to the root directory of the project
